[package]
name = "zeckendorf"
version = "0.1.0"
edition = "2024"

[lib]
name = "zeckendorf_rs"
path = "src/lib.rs"

[features]
default = []
plotting = ["dep:plotters"]

[dependencies]
bitvec = "1.0.1"
num-bigint = "0.4.6"
num-format = { version = "0.4.4", features = ["num-bigint"] }
num-traits = "0.2.19"
plotters = { version = "0.3.7", optional = true }
rand = "0.9.2"

[[bin]]
name = "generate_data"
path = "src/bin/generate_data.rs"

[[bin]]
name = "plot"
path = "src/bin/plot.rs"
required-features = ["plotting"]

[[bin]]
name = "generate_statistics"
path = "src/bin/generate_statistics.rs"
required-features = ["plotting"]

[[bench]]
name = "zeckendorf_bench"
harness = false

[[bench]]
name = "fibonacci_bench"
harness = false

[dev-dependencies]
criterion = { version = "0.8.1", features = ["csv_output", "html_reports"] }
